language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0

before_script:
  - composer install
  - composer dumpautoload
  - bash vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
