language: php

php:
  - 5.5.9
  - 5.6
  - 7.0

env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - composer install --dev --no-interaction
  - bash vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - bash <(curl -s https://codecov.io/bash)

script: phpunit
